"""Remove graph_image column from DiagnosisResult

Revision ID: 8725d1d0fa45
Revises: fce050416768
Create Date: 2025-05-04 11:21:33.331957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8725d1d0fa45'
down_revision = 'fce050416768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis_result', schema=None) as batch_op:
        batch_op.drop_column('graph_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('graph_image', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
